services: couchdb
language: ruby
rvm: 2.1
install:
- curl -X PUT -d '"false"' localhost:5984/_config/httpd/secure_rewrites
- curl -X PUT localhost:5984/tire-a-part
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- sudo pip install couchapp
- couchapp push . http://localhost:5984/tire-a-part
- gem install capybara-webkit rspec
script: xvfb-run rspec spec/features/*
