services: couchdb
language: ruby
rvm: 2.1.0
install:
- curl -X PUT -d '"false"' localhost:5984/_config/httpd/secure_rewrites
- curl -X PUT localhost:5984/tire-a-part
- curl -O http://python-distribute.org/distribute_setup.py
- sudo python distribute_setup.py
- sudo easy_install couchapp
- rm -f distribute-*.tar.gz
- couchapp push . http://localhost:5984/tire-a-part
- gem install capybara-webkit rspec
script: xvfb-run rspec spec/features/*
